name: Build GlowEQ Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-apk:
    name: Build Kivy Android APK
    runs-on: ubuntu-22.04

    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configurar Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Instalar dependências do sistema e Buildozer
      - name: Install Buildozer & system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip \
            python3-setuptools python3-wheel python3-venv \
            libffi-dev libssl-dev autoconf automake \
            libtool pkg-config libsqlite3-dev zlib1g-dev \
            libncurses5-dev libncursesw5-dev \
            libreadline-dev libgdbm-dev libdb5.3-dev \
            libbz2-dev libexpat1-dev liblzma-dev \
            libffi-dev libmpdec-dev
          git --version
          pip install --upgrade pip
          pip install buildozer cython

      # 3.1️⃣ Instalar Android SDK + Build Tools corretamente
      - name: Install Android SDK and Build Tools
        run: |
          export ANDROID_HOME=$HOME/Android/Sdk
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O tools.zip
          unzip -q tools.zip
          # mover conteúdo interno cmdline-tools para latest
          mkdir -p $ANDROID_HOME/cmdline-tools/latest
          mv cmdline-tools/* $ANDROID_HOME/cmdline-tools/latest/
          # atualizar PATH para sdkmanager
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
          # aceitar licenças
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME --licenses || true
          # instalar platform-tools, platforms e build-tools (inclui aidl)
          $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      # 4️⃣ Compilar APK
      - name: Build APK with Buildozer
        working-directory: ./
        run: |
          buildozer android debug
        env:
          PATH: /usr/bin:$PATH:/home/runner/.local/bin:$HOME/Android/Sdk/platform-tools:$HOME/Android/Sdk/cmdline-tools/latest/bin
          ANDROIDSDK: $HOME/Android/Sdk
          ANDROIDNDK: /home/runner/.buildozer/android/platform/android-ndk-r25b

      # 5️⃣ Upload APK gerado
      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: GlowEQ-debug-apk
          path: bin/*.apk
