name: Build GlowEQ Android APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # permite executar manualmente no GitHub Actions

jobs:
  build-apk:
    name: Build Kivy Android APK
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Buildozer & dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk python3-pip \
            python3-setuptools python3-wheel python3-venv \
            libffi-dev libssl-dev autoconf automake \
            libtool pkg-config libsqlite3-dev zlib1g-dev \
            libncurses5-dev libncursesw5-dev \
            libreadline-dev libgdbm-dev libdb5.3-dev \
            libbz2-dev libexpat1-dev liblzma-dev \
            libffi-dev libmpdec-dev
          pip install --upgrade pip
          pip install buildozer cython

      - name: Build APK with Buildozer
        run: |
          buildozer android debug
        env:
          ANDROIDSDK: /home/runner/.buildozer/android/platform/android-sdk
          ANDROIDNDK: /home/runner/.buildozer/android/platform/android-ndk-r25b
          PATH: /home/runner/.local/bin:$PATH

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: GlowEQ-debug-apk
          path: bin/*.apk
